server:
  port: 8080
  compression:
    enabled: true
  servlet:
    session:
      timeout: 3600s
      cookie:
        max-age: 36000s
#集群节点
elasticsearch:
    nodes: 192.168.1.X1:9200,192.168.1.X2:9200,192.168.1.X3:9200
